name: Selenium Test

on:
  push:
    branches: [ "main", "ci-test" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # - uses: actions/checkout@v3

      # - uses: actions/setup-node@v3
      #   with:
      #     node-version: 20

      # - name: Install dependencies
      #   run: npm install
      #   working-directory: my-app

      # - name: Setup Chrome
      #   uses: browser-actions/setup-chrome@v1

      # - name: Run Selenium Test
      #   run: node tests/auth/login.test.js tests/post/post.test.js tests/logout/logout.test.js
      #   working-directory: my-app

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_VM_IP }} >> ~/.ssh/known_hosts

      - name: Copy project to VM
        run: |
          scp -r . ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }}:~/social-media

      - name: Run Selenium on VM
        run: |
          ssh ${{ secrets.GCP_VM_USER }}@${{ secrets.GCP_VM_IP }} << 'EOF'
            cd ~/social-media/my-app
            npm install
            node tests/auth/login.test.js
          EOF