name: Selenium Test

on:
  push:
    branches: [ "main", "ci-test" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install
        working-directory: my-app

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run Selenium Test
        run: node tests/auth/login.test.js tests/post/post.test.js tests/logout/logout.test.js
        working-directory: my-app